### Run triggerNotification action. This will send notification to MS Teams
POST http://localhost:4004/api/triggerNotification
Content-Type: application/json
Authorization: Basic chandan21own:1234

{ }

### productListing
POST http://localhost:4004/api/productListing
Content-Type: application/json
Authorization: Basic rajesh:1234

{ 
    "productPlant": {
        "product_id" : "19091",
        "plant_id": "1051",
        "validFrom": "2022-01-01T00:00:00Z",
        "validTo": "2022-12-31T00:00:00Z"
    }
}

### Get listing
GET http://localhost:4004/api/ProductPlant_Listing
Content-Type: application/json
x-csrf-token: fetch
Authorization: Basic chandan21own:1234

{ }

### Submit Orders
POST http://localhost:4004/browse/Orders
Content-Type: application/json

{ "OrderNo":"2019-09...", "Items":[
    { "book_ID":201, "amount":5 }
]}

### Check books entity that stock was reduced
GET http://localhost:4004/browse/Books