### Run triggerNotification action. This will send notification to MS Teams
POST http://localhost:4004/api/triggerNotification
Content-Type: application/json

{ }

### Run triggerNotification action. This will send notification to MS Teams
GET http://localhost:4004/api/ProductPlant_Listing
Content-Type: application/json
x-csrf-token: fetch

{ }

### Submit Orders
POST http://localhost:4004/browse/Orders
Content-Type: application/json

{ "OrderNo":"2019-09...", "Items":[
    { "book_ID":201, "amount":5 }
]}

### Check books entity that stock was reduced
GET http://localhost:4004/browse/Books